---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  # use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: ubuntu-14.04
  - name: centos-7.0
  - name: centos-6.4
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - "recipe[openstack-mistral::default]"
    attributes:
  - name: database
    run_list:
      - "recipe[openstack-mistral::_database]"
    attributes:
