name             'openstack-mistral'
maintainer       'StackStorm (st2-dev)'
maintainer_email 'info@stackstorm.com'
license          'Apache 2.0'
description      'Installs/Configures openstack-mistral'
long_description 'Installs/Configures openstack-mistral'
version          '0.3.0'

depends 'mysql'
depends 'packagecloud'
depends 'apt'
