name             'openstack-mistral'
maintainer       'StackStorm (st2-dev)'
maintainer_email 'info@stackstorm.com'
license          'Apache 2.0'
description      'Installs/Configures openstack-mistral'
long_description 'Installs/Configures openstack-mistral'
version          '0.2.2'

depends 'build-essential'
depends 'python'
depends 'git'
depends 'mysql'
